version: "3.8"

services:
  db:
    build: ./mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bucketlist   # must match your app config
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flasknet

  web:
    build: ./flaskapp
    container_name: flask-app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MYSQL_DATABASE_USER: flaskuser
      MYSQL_DATABASE_PASSWORD: flaskpass
      MYSQL_DATABASE_DB: bucketlist
      MYSQL_DATABASE_HOST: db   # service name of MySQL container
    ports:
      - "5002:5002"

    networks:
      - flasknet

networks:
  flasknet:

volumes:
  db_data:
